# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          APPLICATION_NAME: netflix
          POSTGRES_DB: db_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          SIDEKIQ_ADMIN: admin
          SIDEKIQ_PASSWORD: admin
          JWT_KEY: just_decoded_password123
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://postgres:password@localhost:5432/db_test"
      JWT_KEY: just_decoded_password123
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      # Add or replace database setup steps here
      - name: Set up database schema
        run: |
          bundle exec rails db:drop
          bundle exec rails db:create
          bundle exec rails db:schema:load
      # Add or replace test runners here
      - name: Run tests
        run: |
           bundle exec rspec spec

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      - name: Install bundler-audit
        run: gem install bundler-audit
      # Add or replace any other lints here
      - name: Security audit dependencies
        run: bundler-audit --update
      - name: Install brakeman
        run: gem install brakeman
      - name: Security audit application code
        run: brakeman -q -w2
